# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8b8a04992082fff1a35d3197b0bb1830"
name = "test"
handle = "test-16003"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "new-wall-discount-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
