# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c310ddf780de83af3ea03b1cc250b01e"
name = "discount-app"
handle = "discount-app-882"
application_url = "https://discount-cavalli-71a6b6a2c05e.herokuapp.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [
  "https://discount-cavalli-71a6b6a2c05e.herokuapp.com/api/auth"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
