api_version = "2024-10"

[[extensions]]
name = "t:name"
handle = "new-cavalli-discount"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/apply-discount"   # Укажите здесь правильный маршрут для создания скидки
  details = "/discount-details" # Укажите здесь правильный маршрут для отображения деталей скидки
